/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_siggi_signalcatcher_SignalCatcher */

#ifndef _Included_io_siggi_signalcatcher_SignalCatcher
#define _Included_io_siggi_signalcatcher_SignalCatcher
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_siggi_signalcatcher_SignalCatcher
 * Method:    doKill
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_io_siggi_signalcatcher_SignalCatcher_doKill
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     io_siggi_signalcatcher_SignalCatcher
 * Method:    startHandlingSignal
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_io_siggi_signalcatcher_SignalCatcher_startHandlingSignal
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
